app/models.py
from datetime import datetime
from . import db


class Block(db.Model):
    __tablename__ = 'blocks'

    id = db.Column(db.Integer, primary_key=True)
    number = db.Column(db.Integer)
    type = db.Column(db.Enum('unset', 'song', 'command', name='block_types'))
    tag_uuid = db.Column(db.String(16))
    song_id = db.Column(db.Integer, db.ForeignKey('songs.id'))
    command_id = db.Column(db.Integer, db.ForeignKey('commands.id'))


class Song(db.Model):
    __tablename__ = 'songs'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(64))
    file = db.Column(db.String(64))
    blocks = db.relationship('Block', backref='song')


class Command(db.Model):
    __tablename__ = 'commands'

    id = db.Column(db.Integer, primary_key=True)
    function = db.Column(db.Text())
    args = db.Column(db.Text())

    blocks = db.relationship('Block', backref='command')


class PlayHistory(db.Model):
    __tablename__ = 'play_history'

    id = db.Column(db.Integer, primary_key=True)
    song_title = db.Column(db.String(64))
    block_number = db.Column(db.Integer)
    time_played = db.Column(db.DateTime(), default=datetime.utcnow)
    length_played = db.Column(db.Interval())

app/main/forms.py
from flask_wtf import Form
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms import StringField, SelectField, SubmitField
from wtforms.validators import DataRequired

from ..models import Block


class ChangeSong(Form):
    file = FileField('File', validators=[FileRequired(), FileAllowed(['mp3'], 'Mp3s only')])
    block_number = SelectField('Block #', validators=[DataRequired()], coerce=int)
    song_title = StringField('Song Title', validators=[DataRequired()])
    submit = SubmitField('Change Song')

    def __init__(self, *args, **kwargs):
        super(ChangeSong, self).__init__(*args, **kwargs)
        self.block_number.choices = [(block.number, block.number)
                                     for block in Block.query.order_by(Block.number).all()]


class AdvancedForm(Form):
    shutdown = SubmitField('Shutdown')
    reboot = SubmitField('Reboot')
    block_number = SelectField('Block #', coerce=int)
    delete = SubmitField('Delete Block')

    def __init__(self, *args, **kwargs):
        super(AdvancedForm, self).__init__(*args, **kwargs)
        self.block_number.choices = [(block.number, block.number)
                                     for block in Block.query.order_by(Block.number).all()]

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from config import config

bootstrap = Bootstrap()
moment = Moment()
db = SQLAlchemy()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    app.jinja_env.trim_blocks = True
    app.jinja_env.lstrip_blocks = True

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .api_1_0 import api as api_1_0_blueprint
    app.register_blueprint(api_1_0_blueprint, url_prefix='/api/v1.0')

    return app

app/api_1_0/__init__.py
import redis
from flask import Blueprint

api = Blueprint('api', __name__)
red = redis.StrictRedis()
status = red.pubsub(ignore_subscribe_messages=True)

from . import player, system

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)

from . import views

app/main/views.py
import subprocess
from flask import url_for, render_template, redirect, flash, current_app
from werkzeug.utils import secure_filename
from sqlalchemy import func
from . import main
from .forms import ChangeSong, AdvancedForm
from .. import db
from ..models import Block, Song, PlayHistory


@main.route('/', methods=['GET', 'POST'])
def index():
    counts = db.session.query(PlayHistory.song_title, func.count('*').
                              label('play_count')).\
        group_by(PlayHistory.song_title).subquery()
    blocks = db.session.query(Block.number, Song.title, counts.c.play_count).\
        join(Song).outerjoin(counts, Song.title == counts.c.song_title).order_by(Block.number).all()
    history_10 = PlayHistory.query.order_by(PlayHistory.time_played.desc()).limit(10)
    return render_template('index.html', blocks=blocks, history=history_10)


@main.route('/advanced', methods=['GET', 'POST'])
def advanced():
    form = AdvancedForm()
    if form.validate_on_submit():
        if form.shutdown.data:
            subprocess.call(['shutdown -h now "System Shutdown from Web"'], shell=True)
            db.session.close()
            flash('System will shutdown now', 'success')
        elif form.reboot.data:
            subprocess.call(['shutdown -r now "System Rebooted from Web"'], shell=True)
            db.session.close()
            flash('System will reboot now', 'success')
        elif form.delete.data:
            block = db.session.query(Block).filter_by(number=form.block_number.data).one()
            db.session.delete(block)
            db.session.commit()
            flash('Block %i deleted' % form.block_number.data, 'success')
        return redirect(url_for('.advanced'))
    return render_template('advanced.html', form=form)


@main.route('/history')
@main.route('/history/<int:page>')
def history(page=1):
    history_pagination = PlayHistory.query.order_by(PlayHistory.time_played.desc()).paginate(page, 25, False)
    return render_template('history.html', history=history_pagination)


@main.route('/manage', methods=['GET', 'POST'])
def manage():
    cs_form = ChangeSong()
    if cs_form.validate_on_submit():
        song_filename = secure_filename(cs_form.file.data.filename)
        song = Song.query.filter_by(file=song_filename).one_or_none()
        if song is None:
            song = Song(title=cs_form.song_title.data, file=song_filename)
            cs_form.file.data.save(current_app.config['MUSICBLOCKS_DIRECTORY'] + song_filename)
            db.session.add(song)
        else:
            song.title = cs_form.song_title.data
        block = Block.query.filter_by(number=cs_form.block_number.data).one()
        block.song = song
        db.session.add(block)
        db.session.commit()
        return redirect(url_for('.manage'))
    blocks = Block.query.order_by(Block.number).all()
    catalog = Song.query.filter_by(blocks=None)
    return render_template('manage.html', blocks=blocks, cs_form=cs_form, catalog=catalog)

app/templates/_macros.html
{% macro pagination_widget(pagination, endpoint, fragment='') %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

app/templates/advanced.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Music Blocks Manager - Advanced{% endblock %}
{% block page_content %}
{{ wtf.quick_form(form, button_map={'shutdown':'primary', 'reboot':'primary', 'delete':'danger'}) }}

{% endblock %}
{% block scripts %}
{{ super() }}
<script>
  $(document).ready(function(){
    var js = "return confirm('Are you sure?  This cannot be undone.');";
    // create a function from the "js" string
    var newclick = new Function(js);

    // clears onclick then sets click using jQuery
    $("#delete").attr('onclick', '').click(newclick);
  });
</script>
{% endblock %}

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Music Blocks Manager{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/7.1.0/css/bootstrap-slider.min.css">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
<script src="https://use.fontawesome.com/c18d6ebe3f.js"></script>
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Music Blocks</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
                <li><a href="{{ url_for('main.manage') }}">Manage</a></li>
                <li><a href="{{ url_for('main.advanced') }}">Advanced</a></li>
                <li><a href="{{ url_for('main.history') }}">History</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container well well-sm">
    <div class="row">
        <div class="col-md-1 col-sm-1 col-xs-1"><span class="fa fa-stack fa-2x"><span class="fa fa-music fa-stack-1x active-icon"></span><span id="ps_active" class="fa fa-ban text-danger fa-stack-2x active-icon"></span></span></div>
        <div class="col-md-4 col-sm-11 col-xs-11 status-bar"><span id="ps_playing"></span></div>
        <div class="col-md-2 col-sm-12 col-xs-12 status-bar"><button id="btn-stop" class="btn btn-danger" type="button" disabled><span class="fa fa-stop"></span>  Stop</button></div>
        <div class="col-md-5 col-sm-12 col-xs-12 status-bar">
            Volume: <span id="ps_volume"></span>
            <input id="input-volume" data-slider-id='volumeSlider' type="text" data-slider-min="0" data-slider-max="100" data-slider-step="1" data-slider-value="50"/>&nbsp;&nbsp;
            <button id="btn-volume" class="btn btn-default" type="button" disabled >Set Volume</button>
        </div>
    </div>
</div>
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/7.1.0/bootstrap-slider.min.js"></script>
<script type="text/javascript" src="{{ url_for('static', filename='script.js') }}"></script>
<script>
$(function(){
    // status_stream = new EventSource('{{ url_for("api.player_state_stream") }}')
    // status_stream.onmessage = function(event){
    //     setPlayerState(JSON.parse(event.data)); }
    statusBarUpdate('{{ url_for("api.player_state") }}');
    $('#btn-volume').click(function(){
        $.post('{{ url_for("api.set_volume") }}',{volume: $('#input-volume').val()});
    });
    $('#btn-stop').click(function(){
        $.post('{{ url_for("api.stop_block") }}');
    });
});
</script>
{% endblock %}

app/templates/history.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title %}Music Blocks Manager - History{% endblock %}
{% block page_content %}
<div class="container">
  <h2 class="sub-header">History</h2>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Date & Time</th>
          <th>Song Name</th>
          <th>Block #</th>
          <th>Length Played</th>
        </tr>
      </thead>
      <tbody>
        {% for row in history.items %}
          <tr>
            <td>{{ moment(row.time_played).format('MMMM Do YYYY, h:mm:ss a') }}</td>
            <td>{{ row.song_title }}</td>
            <td>{{ row.block_number }}</td>
            <td>{{ row.length_played }}
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
<ul class="pagination">
  {{ macros.pagination_widget(history, 'main.history') }}
</ul>
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}Music Blocks Manager - Index{% endblock %}
{% block page_content %}
<div class="container">
  <h1 class="header">Music Blocks Manager</h1>
  <h2 class="sub-header">Current Songs</h2>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Play</th>
          <th>Block #</th>
          <th>Song Name</th>
          <th>Play Count</th>
        </tr>
      </thead>
      <tbody>
        {% for ablock in blocks %}
          <tr>
            <td><button name="id" type="button" class="btn btn-default playButton" value="{{ ablock.number }}">Play</button></td>
            <td>{{ ablock.number }}</td>
            <td>{{ ablock.title }}</td>
            <td>{{ ablock.play_count }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <h2 class="sub-header">Recent History</h2>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Date & Time</th>
          <th>Song Name</th>
          <th>Block #</th>
          <th>Length Played</th>
        </tr>
      </thead>
      <tbody>
        {% for row in history %}
          <tr>
            <td>{{ moment(row.time_played).format('MMMM Do YYYY, h:mm:ss a') }}</td>
            <td>{{ row.song_title }}</td>
            <td>{{ row.block_number }}</td>
            <td>{{ row.length_played }}
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

    </br></br>
</div>
{% endblock %}
{% block scripts %}
{{ super() }}
<script>
$(function(){
    $('.playButton').click(function(){
        $.post('{{ url_for('api.execute_block') }}', {block_number: $(this).attr('value')});
    });
});
</script>
{% endblock %}

app/templates/manage.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Music Blocks Manager - Manage {% endblock %}
{% block page_content %}
<h2 class="header">Reorder Blocks</h2>
        <div class="container-fluid text-center">
            <div class="row">
                    <div class="col-md-2 col-sm-4 col-xs-6">
                        <div class="row">
                            <div class="col-md-12"><h3>Block #</h3></div>
                        </div>
                        <div class="list-group">
                            {% for block in blocks %}
                            <div class="row list-group-item">
                                <div class="col-md-12">{{ block.number }}</div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-6">
                        <div class="row">
                            <div class="title-blocks col-md-12"><h3>Song Name</h3></div>
                        </div>
                        <div id="blocks_list" class="list-group">
                            {% for block in blocks %}
                            <div class="row list-group-item">
                                <div class="title-blocks col-md-12"><input class="blocks-list-item" type="hidden" value="{{ block.song.id }}">{{ block.song.title }}</div>
                            </div>
                            {% endfor %}
			    {% for song in catalog %}
                            <div class="row list-group-item">
                                <div class="title-blocks col-md-12"><input class="blocks-list-item" type="hidden" value="{{ song.id }}">{{ song.title }}</div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
            </div>
        </div>
        <div>
            <br/>
            <button id="btn-reorder" class="btn btn-primary" role="button">Reorder Blocks</button>
        </div>
    <div class="container-fluid">
    <h2 class="sub-header">Change Song</h2>
    <form class="form form-horizontal" method="post" enctype="multipart/form-data" role="form">
      {{ cs_form.hidden_tag() }}
      {{ wtf.form_errors(cs_form, hiddens="only") }}
      {{ wtf.form_field(cs_form.block_number, form_type="horizontal", horizontal_columns=('md',1,1)) }}
      {{ wtf.form_field(cs_form.song_title, form_type="horizontal", horizontal_columns=('md',1,6)) }}
      {{ wtf.form_field(cs_form.file, form_type="horizontal", horizontal_columns=('md',1,11)) }}
      {{ wtf.form_field(cs_form.submit, form_type="horizontal", horizontal_columns=('md',1,11), button_map={'submit':'primary'}) }}
    </form>
</div>
    <br/>
    <br/>
{% endblock %}

{% block scripts %}
{{ super() }}
<!-- Latest Sortable -->
<script src="http://rubaxa.github.io/Sortable/Sortable.js"></script>
<script>
    Sortable.create(blocks_list);
    $('#btn-reorder').click(function(){
        var data = {'songs':[]};
        $('.blocks-list-item').each(function(index){
            block = {};
            block['number'] = index+1;
            block['song'] = parseInt($(this).val());
            data['songs'].push(block);
        });
        $.ajax({
            type: 'POST',
            url: '{{ url_for("api.reorder_blocks") }}',
            data: JSON.stringify(data),
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            success: function(){location.reload();}
        });
    });
</script>
{% endblock %}